apiVersion: apps/v1
kind: Deployment
metadata:
  name: springbootbestpracticeskit
spec:
  replicas: 2
  selector:
    matchLabels:
      app: springbootbestpracticeskit
  template:
    metadata:
      labels:
        app: springbootbestpracticeskit
    spec:
      containers:
        - name: app
          image: alibnh/springbootbestpracticeskit:1.0
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_DATASOURCE_URL
              value: jdbc:postgresql://db:5432/crud
            - name: SPRING_DATASOURCE_USERNAME
              value: postgres
            - name: SPRING_DATASOURCE_PASSWORD
              value: postgres
            - name: SPRING_DATASOURCE_DRIVER_CLASS_NAME
              value: org.postgresql.Driver
